import { DECK_SIZE, type CardId } from "@mario-cards/shared";

/** Which tab a challenge lives in: as the Villain you face heroes decks,
 * as the Heroes you face heroes decks. */
export type ChallengeSide = "villains" | "heroes";

/** A boss battle: the CPU plays a fixed themed deck fronted by its boss. */
export interface Challenge {
  id: string;
  name: string;
  boss: CardId;
  description: string;
  side: ChallengeSide;
  deck: CardId[];
}

/** Themed 16-card boss decks (2-special max, like player decks). */
export const CHALLENGES: Challenge[] = [
  {
    id: "goombas",
    name: "Goombas",
    boss: "grand-goomba",
    description: "The goomba stampede: no specials, all teeth.",
    side: "villains",
    deck: [
      "goomba",
      "goomba",
      "goomba",
      "paragoomba",
      "paragoomba",
      "gloomba",
      "gloomba",
      "Galoomba",
      "Galoomba",
      "winged-Galoomba",
      "winged-Galoomba",
      "cat-goomba",
      "cat-goomba",
      "grand-goomba",
      "grand-goomba",
      "grand-Galoomba",
    ],
  },
  {
    id: "koopas",
    name: "Koopas",
    boss: "koopa-troopa",
    description: "Shells and spikes: the koopa troop, no specials.",
    side: "villains",
    deck: [
      "koopa-troopa",
      "koopa-troopa",
      "koopa-troopa",
      "koopa-paratroopa",
      "koopa-paratroopa",
      "dry-bones",
      "dry-bones",
      "paradrybones",
      "spike",
      "spike",
      "spike2",
      "spike2",
      "lakitu",
      "lakitu",
      "chargin-chuck",
      "chargin-chuck",
    ],
  },
  {
    id: "king-bob-omb",
    name: "King Bob-omb",
    boss: "king-bob-omb",
    description: "Explosives royalty: bombs and every kind of bullet.",
    side: "villains",
    deck: [
      "king-bob-omb",
      "bob-omb",
      "bob-omb",
      "bob-omb",
      "para-bomb",
      "para-bomb",
      "para-bomb",
      "bullet-bill",
      "bullet-bill",
      "bullet-bill",
      "cat-bullet-bill",
      "cat-bullet-bill",
      "cat-bullet-bill",
      "banzai-bill",
      "banzai-bill",
      "banzai-bill",
    ],
  },
  {
    id: "king-boo",
    name: "King Boo",
    boss: "king-boo",
    description: "Haunted house: boos and the undead crew.",
    side: "villains",
    deck: [
      "king-boo",
      "boo",
      "boo",
      "boo",
      "boo",
      "big-boo",
      "big-boo",
      "big-boo",
      "dry-bones",
      "dry-bones",
      "dry-bones",
      "dry-bones",
      "paradrybones",
      "paradrybones",
      "paradrybones",
      "gloomba",
    ],
  },
  {
    id: "dino-piranha",
    name: "Dino Piranha",
    boss: "dino-piranha",
    description: "Overgrowth: every piranha and pokey, one lone boss.",
    side: "villains",
    deck: [
      "snow-pokey",
      "snow-pokey",
      "snow-pokey",
      "piranha-plant",
      "piranha-plant",
      "piranha-creeper",
      "piranha-creeper",
      "pokey",
      "pokey",
      "pokeyplant",
      "pokeyplant",
      "venus-fire-trap",
      "venus-fire-trap",
      "spiny-piranha-plant",
      "spiny-piranha-plant",
      "dino-piranha",
    ],
  },
  {
    id: "bowser-jr",
    name: "Bowser Jr.",
    boss: "bowser-jr",
    description: "The koopa army, with Magikoopa as the second special.",
    side: "villains",
    deck: [
      "bowser-jr",
      "magikoopa",
      "koopa-troopa",
      "koopa-troopa",
      "koopa-troopa",
      "koopa-paratroopa",
      "koopa-paratroopa",
      "dry-bones",
      "dry-bones",
      "spike",
      "spike",
      "spike2",
      "spike2",
      "chargin-chuck",
      "chargin-chuck",
      "lakitu",
    ],
  },
  {
    id: "bowser",
    name: "Bowser",
    boss: "bowser",
    description:
      "The Koopa King's full army: three specials and a wall of shells.",
    side: "villains",
    deck: [
      "dry-bones",
      "dry-bones",
      "koopa-troopa",
      "koopa-troopa",
      "koopa-troopa",
      "spike",
      "lakitu",
      "bullet-bill",
      "koopa-paratroopa",
      "koopa-paratroopa",
      "chargin-chuck",
      "hammer-bro",
      "bowser-jr",
      "magikoopa",
      "sledge-bro",
      "bowser",
    ],
  },
  {
    id: "bowsers-fury",
    name: "Bowser's Fury",
    boss: "fury-bowser",
    description:
      "The Koopa dynasty unleashed: five bosses over a shell wall.",
    side: "villains",
    deck: [
      "dry-bones",
      "dry-bones",
      "dry-bones",
      "spiny",
      "koopa-troopa",
      "koopa-troopa",
      "koopa-troopa",
      "lakitu",
      "koopa-paratroopa",
      "koopa-paratroopa",
      "chargin-chuck",
      "bowser-jr",
      "bowser-jr-bust",
      "magikoopa",
      "bowser",
      "fury-bowser",
    ],
  },
  {
    id: "toad",
    name: "Toad",
    boss: "blue-toad",
    description: "The toad patrol: every color, no specials.",
    side: "heroes",
    deck: [
      "blue-toad",
      "blue-toad",
      "blue-toad",
      "blue-toad",
      "purple-toad",
      "purple-toad",
      "purple-toad",
      "purple-toad",
      "red-toad",
      "red-toad",
      "red-toad",
      "red-toad",
      "yellow-toad",
      "yellow-toad",
      "yellow-toad",
      "yellow-toad",
    ],
  },
  {
    id: "captain-toad",
    name: "Captain Toad",
    boss: "captain-toad",
    description: "The Toad Brigade on expedition.",
    side: "heroes",
    deck: [
      "captain-toad",
      "yellow-toad",
      "blue-toad",
      "blue-toad",
      "blue-toad",
      "blue-toad",
      "purple-toad",
      "purple-toad",
      "purple-toad",
      "red-toad",
      "red-toad",
      "red-toad",
      "red-toad",
      "yellow-toad",
      "yellow-toad",
      "yellow-toad",
    ],
  },
  {
    id: "plessie",
    name: "Plessie",
    boss: "plessiee",
    description: "River rapids: Plessie and the whole fish crew.",
    side: "heroes",
    deck: [
      "plessiee",
      "cheep-cheep",
      "cheep-cheep",
      "cheep-cheep",
      "cheep-cheep",
      "blooper",
      "blooper",
      "blooper",
      "blooper",
      "blooper",
      "splounder",
      "splounder",
      "splounder",
      "splounder",
      "splounder",
      "splounder",
    ],
  },
  {
    id: "rosaline-galaxy",
    name: "Rosaline Galaxy",
    boss: "rosaline",
    description: "Cosmic guardian: Rosaline and the Galaxy crew.",
    side: "heroes",
    deck: [
      "rosaline",
      "luma",
      "luma",
      "luma",
      "luma",
      "luma",
      "blue-luma",
      "blue-luma",
      "blue-luma",
      "blue-luma",
      "blue-luma",
      "star-bunny",
      "star-bunny",
      "star-bunny",
      "star-bunny",
      "star-bunny",
    ],
  },
  {
    id: "queen-bee",
    name: "Queen Bee",
    boss: "queen-bee",
    description: "The hive queen and her Galaxy swarm.",
    side: "heroes",
    deck: [
      "queen-bee",
      "bee",
      "bee",
      "bee",
      "bee",
      "bee",
      "luma",
      "luma",
      "luma",
      "luma",
      "luma",
      "blue-luma",
      "blue-luma",
      "blue-luma",
      "blue-luma",
      "blue-luma",
    ],
  },
  {
    id: "toadette",
    name: "Toadette",
    boss: "toadette",
    description: "Mushroom royalty: Toadette with Toad at her side.",
    side: "heroes",
    deck: [
      "toadette",
      "toad",
      "blue-toad",
      "blue-toad",
      "blue-toad",
      "blue-toad",
      "purple-toad",
      "purple-toad",
      "purple-toad",
      "red-toad",
      "red-toad",
      "red-toad",
      "red-toad",
      "yellow-toad",
      "yellow-toad",
      "yellow-toad",
    ],
  },
  {
    id: "mario-brothers",
    name: "Mario Brothers",
    boss: "luigi",
    description: "Mario and Luigi with the Mushroom Kingdom crew.",
    side: "heroes",
    deck: [
      "mario",
      "luigi",
      "red-toad",
      "red-toad",
      "blue-toad",
      "blue-toad",
      "yellow-toad",
      "yellow-toad",
      "purple-toad",
      "koopa-troopa",
      "koopa-troopa",
      "dry-bones",
      "goomba",
      "goomba",
      "Galoomba",
      "Galoomba",
    ],
  },
  {
    id: "kongs-family",
    name: "Kong's Family",
    boss: "donkey-kong",
    description: "The Kong crew swings in with a jungle barrel brawl.",
    side: "heroes",
    deck: [
      "spiny-skipsqueak",
      "spiny-skipsqueak",
      "bob-omb",
      "bob-omb",
      "conkdor",
      "conkdor",
      "monty-mole",
      "monty-mole",
      "diddy-kong",
      "rocky-wrench",
      "rocky-wrench",
      "wiggler",
      "wiggler",
      "dixie-kong",
      "banzai-bill",
      "donkey-kong",
    ],
  },
  {
    id: "yoshis-island",
    name: "Yoshi's Island",
    boss: "yoshi",
    description: "Every Yoshi rides out, backed by the koopa troop.",
    side: "heroes",
    deck: [
      "koopa-troopa",
      "koopa-troopa",
      "koopa-troopa",
      "koopa-troopa",
      "koopa-troopa",
      "lakitu",
      "lakitu",
      "lakitu",
      "koopa-paratroopa",
      "koopa-paratroopa",
      "koopa-paratroopa",
      "koopa-paratroopa",
      "yoshi",
      "blue-yoshi",
      "red-yoshi",
      "yellow-yoshi",
    ],
  },
  {
    id: "princess-union",
    name: "Princess Union",
    boss: "peach",
    description: "The four crowns unite, guarded by toads and lumas.",
    side: "heroes",
    deck: [
      "luma",
      "luma",
      "blue-luma",
      "blue-luma",
      "blue-toad",
      "blue-toad",
      "purple-toad",
      "purple-toad",
      "red-toad",
      "red-toad",
      "yellow-toad",
      "yellow-toad",
      "peach",
      "daisy",
      "pauline",
      "rosaline",
    ],
  },
  {
    id: "3d-world-team",
    name: "3DW Team",
    boss: "mario",
    description: "The heroes suit up with the whole 3D World crew.",
    side: "heroes",
    deck: [
      "skipsqueak",
      "Galoomba",
      "ant-trooper",
      "cat-goomba",
      "spiny",
      "blurker",
      "piranha-creeper",
      "splounder",
      "walleye",
      "goomba-stack",
      "grand-Galoomba",
      "toad",
      "peach",
      "luigi",
      "rosaline",
      "mario",
    ],
  },
];

/** Challenge decks double as playable decks. The first challenge of each
 * side is unlocked from the start; every other deck unlocks by beating
 * its challenge — win them all to own them all. */
export function isChallengeDeckUnlocked(
  challenge: Challenge,
  done: Record<string, boolean>
): boolean {
  if (done[challenge.id]) return true;
  return CHALLENGES.find((c) => c.side === challenge.side)?.id === challenge.id;
}

for (const challenge of CHALLENGES) {
  if (challenge.deck.length !== DECK_SIZE) {
    throw new Error(
      `Challenge "${challenge.id}" deck has ${challenge.deck.length} cards, expected ${DECK_SIZE}`
    );
  }
}
